create table data_replacements
(
    id          bigint generated by default as identity
        primary key,
    category    integer not null
        constraint fk_category
            references system_categories,
    placeholder varchar not null,
    value       text    not null
);

INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (22, 1, 'OVERALL_CATEGORY_KEY_BASE', 'ПДн');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (25, 1, 'OVERALL_CATEGORY_KEY_FULL', 'персональных данных');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (26, 2, 'OVERALL_CATEGORY_KEY_FULL', 'информации');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (19, 1, 'OVERALL_CATEGORY_KEY', 'ПДн');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (11, 3, 'PURPOSE_4_1_3',
        'В документе не рассматриваются методические подходы по оценке угроз безопасности информации, обрабатываемой в КИИ, связанных с нарушением безопасности шифровальных (криптографических) средств защиты, а также угроз, связанных с техническими каналами утечки информации.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (15, 3, 'PURPOSE_4_1_5',
        'информации, обрабатываемой в критической информационной инфраструктуре, нормативно-правовых актов и методических документов, регулирующих такую защиту;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (7, 1, 'PURPOSE_4_1_3',
        'В документе не рассматриваются методические подходы по оценке угроз безопасности ПДн, связанных с нарушением безопасности шифровальных (криптографических) средств защиты ПДн, а также угроз, связанных с техническими каналами утечки ПДн.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (18, 3, 'PURPOSE_4_1_6', 'которые могут повлиять на состав или актуальность угроз безопасности информации;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (3, 2, 'PURPOSE_4_1_1',
        'Модель угроз определяет перечень угроз безопасности данных, актуальных для информационно-телекоммуникационной сети ${customerName}, в рамках которой развернута ГИС.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (6, 3, 'PURPOSE_4_1_2',
        'Модель угроз содержит краткое описание архитектуры КИИ, характеристику источников угроз безопасности данных, в том числе модель нарушителя, и описание всех угроз безопасности данных, актуальных для КИИ.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (4, 2, 'PURPOSE_4_1_2',
        'Модель угроз содержит краткое описание архитектуры ГИС, характеристику источников угроз безопасности данных, в том числе модель нарушителя, и описание всех угроз безопасности данных, актуальных для ГИС.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (1, 1, 'PURPOSE_4_1_1',
        'Модель угроз определяет перечень угроз безопасности ПДн, актуальных для информационно-телекоммуникационной сети ${customerName}, в рамках которой развернуты ИСПДн.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (5, 3, 'PURPOSE_4_1_1',
        'Модель угроз определяет перечень угроз безопасности данных, актуальных для информационно-телекоммуникационной сети ${customerName}, в рамках которой развернута критическая информационная инфраструктура (КИИ).');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (9, 2, 'PURPOSE_4_1_3',
        'В документе не рассматриваются методические подходы по оценке угроз безопасности информации, обрабатываемой в ГИС, связанных с нарушением безопасности шифровальных (криптографических) средств защиты, а также угроз, связанных с техническими каналами утечки информации.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (17, 2, 'PURPOSE_4_1_6', 'которые могут повлиять на состав или актуальность угроз безопасности информации;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (24, 3, 'OVERALL_CATEGORY_KEY_BASE', 'информация');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (13, 1, 'PURPOSE_4_1_5', 'ПДн, нормативно-правовых актов и методических документов, регулирующих защиту ПДн;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (16, 1, 'PURPOSE_4_1_6', 'которые могут повлиять на состав или актуальность угроз безопасности ПДн;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (14, 2, 'PURPOSE_4_1_5',
        'информации, обрабатываемой в государственных информационных системах, нормативно-правовых актов и методических документов, регулирующих такую защиту;');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (21, 3, 'OVERALL_CATEGORY_KEY', 'информации');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (23, 2, 'OVERALL_CATEGORY_KEY_BASE', 'информация');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (27, 3, 'OVERALL_CATEGORY_KEY_FULL', 'информации');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (2, 1, 'PURPOSE_4_1_2',
        'Модель угроз содержит краткое описание архитектуры ИСПДн, характеристику источников угроз безопасности ПДн, в том числе модель нарушителя, и описание всех угроз безопасности ПДн, актуальных для ИСПДн.');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (20, 2, 'OVERALL_CATEGORY_KEY', 'информации');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (8, 1, 'PURPOSE_4_1_4',
        'Угрозы безопасности ПДн, содержащиеся в настоящей Модели угроз, могут уточняться и дополняться по мере выявления новых источников угроз, развития способов и средств реализации угроз безопасности ПДн');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (10, 2, 'PURPOSE_4_1_4',
        'Угрозы безопасности информации, содержащиеся в настоящей Модели угроз, могут уточняться и дополняться по мере выявления новых источников угроз, развития способов и средств реализации угроз безопасности информации');
INSERT INTO threat_and_sec_schema.data_replacements (id, category, placeholder, value)
VALUES (12, 3, 'PURPOSE_4_1_4',
        'Угрозы безопасности информации, содержащиеся в настоящей Модели угроз, могут уточняться и дополняться по мере выявления новых источников угроз, развития способов и средств реализации угроз безопасности информации');
