create table offenders_reasons
(
    id       bigint generated by default as identity
        constraint offenders_reason_pkey
            primary key,
    offender bigint not null
        constraint offenders_reason_offender_fkey
            references offenders,
    reason   text   not null
);

INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (1, 1,
        'не обладают достаточной мотивацией для нарушения свойств безопасности информации в ${customerName}, так как защищаемая информация не затрагивает интересов других государств.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (2, 2,
        'дорожат своей деловой репутацией и не заинтересованы в возникновении уязвимостей, которые могли бы нанести ущерб их клиентам или подорвать доверие к их продукции.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (3, 3,
        'ценят свою репутацию и действуют в рамках договорных обязательств; преднамеренное создание уязвимостей или саботаж могут привести к серьезным правовым и финансовым последствиям.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (4, 4,
        'сосредоточены на качестве и стабильности услуг; уязвимости и сбои наносят вред их репутации и конкурентоспособности, возможны штрафные санкции и судебные иски.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (5, 5,
        'чаще нацелены на политические, идеологические или социальные цели, не связанные непосредственно с информацией ${customerName}; отсутствует конкретный интерес к этим данным.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (6, 6,
        'ориентированы на прямую финансовую выгоду и обычно выбирают иные объекты для атак; информация ${customerName} не имеет для них существенной материальной ценности;');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (7, 7,
        'не имеют существенного конкурентного интереса к данным ${customerName} и дорожат репутацией; незаконное получение информации чревато крупными рисками и ответственностью.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (8, 8,
        'хотя и обладают высоким уровнем доступа, как правило, подчиняются внутренним регламентам, разделению полномочий и контролю; ценят свою работу и репутацию, не заинтересованы в нарушениях.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (9, 9,
        'не видит потенциальной выгоды или не обладает достаточными навыками для успешного взлома систем ${customerName}; реализованы меры защиты (мониторинг, блокировка подозрительных действий).');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (10, 10,
        'как правило, не обладают достаточными техническими компетенциями и широкими правами доступа; не заинтересованы в умышленных нарушениях, т. к. дорожат работой.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (11, 11,
        'нмеют чётко разграниченные права и подконтрольны средствам внутреннего мониторинга; не заинтересованы в нарушениях, поскольку это влечёт дисциплинарную и/или правовую ответственность.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (12, 12,
        'после увольнения теряют учётные записи и пропуска; связаны соглашениями о неразглашении (NDA), а любые попытки неправомерного доступа влекут правовую ответственность.');
INSERT INTO threat_and_sec_schema.offenders_reasons (id, offender, reason)
VALUES (13, 13,
        'Действуют на основании договоров или поручений, их работа регламентирована и контролируется; на время выполнения работ предоставляются ограниченные по объёму и времени доступы. Нарушение требований безопасности может привести к расторжению договора, финансовым санкциям и репутационным потерям.');
