create table offenders
(
    id   bigint generated by default as identity
        primary key,
    name varchar
);

INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (1, 'Специальные службы иностранных государств');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (2, 'Разработчики, производители, поставщики программных, технических и программно-технических средств');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (3, 'Лица, обеспечивающие поставку программных, программно-аппаратных средств, обеспечивающих систем');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (4, 'Поставщики вычислительных услуг, услуг связи');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (5, 'Террористические, экстремистские группировки');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (6, 'Преступные группы (два лица и более, действующие по единому плану)');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (7, 'Конкурирующие организации');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (8, 'Системные администраторы и администраторы безопасности');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (9, 'Физическое лицо (хакер)');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (10, 'Лица, обеспечивающие функционирование систем и сетей (администрация, охрана, уборщики и т. д.)');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (11, 'Авторизованные пользователи систем и сетей');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (12, 'Бывшие работники (пользователи)');
INSERT INTO threat_and_sec_schema.offenders (id, name)
VALUES (13, 'Лица, привлекаемые для установки, настройки, испытаний');
