create table system_categories
(
    id   integer generated by default as identity
        primary key,
    name varchar
        unique
);

INSERT INTO threat_and_sec_schema.system_categories (id, name)
VALUES (3, 'КИИ');
INSERT INTO threat_and_sec_schema.system_categories (id, name)
VALUES (2, 'ГИС');
INSERT INTO threat_and_sec_schema.system_categories (id, name)
VALUES (1, 'ИСПДн');
